spring:
  datasource:
    url: jdbc:h2:file:./h2-db/job-data;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console